### ISSUE TITLE
[Problem] MPF.Check doesn't seem to work on PSP dumps made with UMDImageCreator?

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/MPF#356]
**Version**
What version are you using? 
- [X] WIP release (2.2-794)

**Build**
- [X] .NET Framework 4.8 running on (Operating System)

**Describe the issue**
I'm trying to run MPF.Check on some UMD dumps I made with UMDImageCreator, and when I do, it says:
```
Error! Please check output directory as dump may be incomplete!
There were files missing from the output:
```

However, there aren't any other files I can think of and it doesn't list anything missing.

**To Reproduce**
1. Dump UMD with UMDImageCreator
2. Run check on the path/iso created
3. Gasp at the error that lies to you!

**Expected behavior**
I expect check to work as normal

**Screenshots**
Available upon request!

**Additional context**
Thanks pal!

**Comment by mnadareski** [comment]
Can you please confirm if adding `-u uic` to your commandline makes this work?

**Comment by sadikyo** [comment]
I tested, and that didn't work either. For reference, my initial command was:

Mpf.check umd psp -c username password "path\to\file.iso"

I just tried

Mpf.check umd psp -c username password -u uic "path\to\file.iso"

and that produced the following error:

Credentials entered, will attempt Redump login...
Credentials accepted! Logged into Redump...
Redump username and password accepted!
Gathering submission information... please wait!
Extracting output information from output files...

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MPF.Library.InfoTool.<ExtractOutputInformation>d__0.MoveNext() in C:\projects\mpf\MPF.Library\InfoTool.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MPF.Library.DumpEnvironment.<VerifyAndSaveDumpOutput>d__39.MoveNext() in C:\projects\mpf\MPF.Library\DumpEnvironment.cs:line 293
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MPF.Check.Program.Main(String[] args) in C:\projects\mpf\MPF.Check\Program.cs:line 194
