### ISSUE TITLE
[Problem] System.NullReferenceException in Datfile generation

### ISSUE THREAD

**Issue by bekoha** [SabreTools/MPF#492]
**Version**
What version are you using? 

- [x] WIP release (2.5-a31d894b)

**Build**
What runtime version are you using?

- [x] .NET Framework 4.8 running on (Windows 10.0.19045)

**Describe the issue**
Left the program running on attempting to dump a DVD of Deus Ex and came back to a window with red error 

~~MPF defaulted to a lower speed than usual (24 is max speed that it generally auto-selected and here it for some reason picked 16 instead), that felt odd~~

```Executing DiscImageCreator... please wait!
DiscImageCreator has finished!
Running any additional tools... see log for output!
No external tools needed!
System.NullReferenceException: Object reference not set to an instance of an object.
   at MPF.Modules.BaseParameters.GenerateDatfile(Datafile datafile) in C:\projects\mpf\MPF.Modules\BaseParameters.cs:line 1094
   at MPF.Modules.DiscImageCreator.Parameters.GenerateSubmissionInfo(SubmissionInfo info, Options options, String basePath, Drive drive, Boolean includeArtifacts) in C:\projects\mpf\MPF.Modules\DiscImageCreator\Parameters.cs:line 399
   at MPF.Library.InfoTool.<ExtractOutputInformation>d__0.MoveNext() in C:\projects\mpf\MPF.Library\InfoTool.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MPF.Library.DumpEnvironment.<VerifyAndSaveDumpOutput>d__40.MoveNext() in C:\projects\mpf\MPF.Library\DumpEnvironment.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MPF.UI.ViewModels.MainViewModel.<StartDumping>d__61.MoveNext() in C:\projects\mpf\MPF\ViewModels\MainViewModel.cs:line 1237
Gathering submission information... please wait!
Extracting output information from output files...
```

Logs and .dat
[dx1_logs.zip](https://github.com/SabreTools/MPF/files/11510789/dx1_logs.zip)

DIC version 20230401 (20230401T144525), .bin filename was passed as an argument but resulting dump was an ISO, "rom name" row missing from the dat

**Comment by mnadareski** [comment]
The difference in speed was confirmed in Discord to be related to Stable vs. WIP build and should be discarded as a potential issue.

**Comment by mnadareski** [comment]
The real issue was that the build of DIC being used was broken, but I am adding some safety around that method for the future anyway.
