### ISSUE TITLE
[Problem] Error in finishing dumping BD-Video

### ISSUE THREAD

**Issue by RedumpPT** [SabreTools/MPF#537]
**Version**

- [ X ] Stable release (2.6.3)

**Build**

- [X ] .NET Framework 4.8 running on (Windows 10)

**Describe the issue**
In the end, MPF gives that error and doesn't compress the logs

**To Reproduce**
Dump BD Video

**Expected behavior**
In the end, it shouldn't give an error and should compress the logs

**Additional context**
DIC dumps the iso OK. I can also submit the logs

MPF error:

```
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at System.ReadOnlySpan`1..ctor(T[] array, Int32 start, Int32 length)
   at MPF.Modules.BaseParameters.<GetLayerbreaks>g__ReadFromArrayBigEndian|87_0(Byte[] bytes, Int32 offset) in B:\Programs\GitHub\MPF\MPF.Modules\BaseParameters.cs:line 1426
   at MPF.Modules.BaseParameters.GetLayerbreaks(PICDiscInformation di, Nullable`1& layerbreak1, Nullable`1& layerbreak2, Nullable`1& layerbreak3) in B:\Programs\GitHub\MPF\MPF.Modules\BaseParameters.cs:line 1435
   at MPF.Modules.DiscImageCreator.Parameters.GenerateSubmissionInfo(SubmissionInfo info, Options options, String basePath, Drive drive, Boolean includeArtifacts) in B:\Programs\GitHub\MPF\MPF.Modules\DiscImageCreator\Parameters.cs:line 480
   at MPF.Library.InfoTool.<ExtractOutputInformation>d__0.MoveNext() in B:\Programs\GitHub\MPF\MPF.Library\InfoTool.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MPF.Library.DumpEnvironment.<VerifyAndSaveDumpOutput>d__40.MoveNext() in B:\Programs\GitHub\MPF\MPF.Library\DumpEnvironment.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MPF.UI.ViewModels.MainViewModel.<StartDumping>d__61.MoveNext() in B:\Programs\GitHub\MPF\MPF\ViewModels\MainViewModel.cs:line 1249
```

Gathering submission information... please wait!
Extracting output information from output files...

after this sentence, MPF doesn't do anything more

**Comment by mnadareski** [comment]
Please try running Check on the outputs to see if it was a temporary hiccup on your machine or not. If it has the same behavior, then I can look into it further.

**Comment by mnadareski** [comment]
Determined to be the result of not using the newest configuration file format.
