### ISSUE TITLE
[Problem] The given key 'InternalSerialName' was not present in the dictionary

### ISSUE THREAD

**Issue by Ragowit** [SabreTools/MPF#703]
**Version**
- [x] Stable release 3.1.9
I have also manually updated redumper to version 329.

**Build**
- [x] .NET 8.0 running on Win 11 23H2

**Describe the issue**
After completing a dump with redumper with the PS3 disc BLES-00189, I get this:
```
Executing Redumper... please wait!
Redumper has finished!
System.Collections.Generic.KeyNotFoundException: The given key 'InternalSerialName' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MPF.Core.Modules.Redumper.Parameters.GenerateSubmissionInfo(SubmissionInfo info, Options options, String basePath, Drive drive, Boolean includeArtifacts)
   at MPF.Core.SubmissionInfoTool.ExtractOutputInformation(String outputPath, Drive drive, Nullable`1 system, Nullable`1 mediaType, Options options, BaseParameters parameters, IProgress`1 resultProgress, IProgress`1 protectionProgress)
   at MPF.Core.DumpEnvironment.VerifyAndSaveDumpOutput(IProgress`1 resultProgress, IProgress`1 protectionProgress, Func`2 processUserInfo, SubmissionInfo seedInfo)
   at MPF.Core.UI.ViewModels.MainViewModel.StartDumping()
Gathering submission information... please wait!
Extracting output information from output files...
```

Log: [SOLDIER OF FORTUNE_ PAYBACK.log](https://github.com/SabreTools/MPF/files/15387582/SOLDIER.OF.FORTUNE_.PAYBACK.log)

**To Reproduce**
Get the PS3 disc BLES-00189, and dump with MPF 3.1.9 and redumper 329

**Expected behavior**
No errors.

**Additional context**
Tried with MPF 3.1.8 and redumper 329, no errors.

**Comment by mnadareski** [comment]
Should be fixed as of https://github.com/SabreTools/MPF/commit/4bb02b88fc830e3850dbf72d4b0515ebde09514d
