### ISSUE TITLE
[Problem] Information gathering fails despite files existing

### ISSUE THREAD

**Issue by Whovian9369** [SabreTools/MPF#755]
**Before You Submit**

**Version**
What version are you using?

- [ ] Stable release (version here)
- [X] WIP release (`3.2.2-8a44fa3355e79a32ee6b8f2d379404a7e8c83d11`)

**Build**
What runtime version are you using?

- [X] .NET 8.0 running on Windows 10

**Describe the issue**
CD Dump using Redumper and DiscImageCreator fails due to files supposedly not existing, despite files being available in directory.

**To Reproduce**

1. Dump CD.
2. Wait for dump to complete.
3. Check MPF log.

**Expected behavior**
Dump information window to appear.

**Logs**
(Renamed from "Screenshots")

<details>
  <summary>Redumper Output</summary>

```
Scanning for drives..
Found 1 drives: D:\
Drive marked as empty, defaulting to CD-ROM.
Supported media speeds: 1, 2, 3, 4, 6, 8, 12, 16, 20, 24, 32, 40, 44, 48, 52, 56, 72
Setting drive speed to: 24
Local version: 3.2.2
Remote version: 3.2.2
You have the newest version!
Changed system to: Apple Macintosh
Starting dumping process... please wait!
Look for the separate command window for more details
Executing Redumper... please wait!
Redumper has finished!
Gathering submission information... please wait!
There were files missing from the output:
ISO\CodeWarrior - Academic Tools 96-97\Disc Not Detected.cue
ISO\CodeWarrior - Academic Tools 96-97\Disc Not Detected.fulltoc
ISO\CodeWarrior - Academic Tools 96-97\Disc Not Detected.log
ISO\CodeWarrior - Academic Tools 96-97\Disc Not Detected.dat
ISO\CodeWarrior - Academic Tools 96-97\Disc Not Detected.scram
ISO\CodeWarrior - Academic Tools 96-97\Disc Not Detected.state
ISO\CodeWarrior - Academic Tools 96-97\Disc Not Detected.subcode
ISO\CodeWarrior - Academic Tools 96-97\Disc Not Detected.toc
```

```
$  ls -1N "ISO/CodeWarrior - Academic Tools 96-97/"
Disc Not Detected.bin
Disc Not Detected.cue
Disc Not Detected.fulltoc
Disc Not Detected.log
Disc Not Detected.scram
Disc Not Detected.state
Disc Not Detected.subcode
Disc Not Detected.toc
```

</details>

<details>
  <summary>DiscImageCreator Output</summary>

```
Scanning for drives..
Found 1 drives: D:\
Drive marked as empty, defaulting to CD-ROM.
Supported media speeds: 1, 2, 3, 4, 6, 8, 12, 16, 20, 24, 32, 40, 44, 48, 52, 56, 72
Setting drive speed to: 24
Local version: 3.2.2
Remote version: 3.2.2
You have the newest version!
Changed system to: Apple Macintosh
Changed dumping program to: DiscImageCreator
Starting dumping process... please wait!
Look for the separate command window for more details
Executing DiscImageCreator... please wait!
DiscImageCreator has finished!
Gathering submission information... please wait!
There were files missing from the output:
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected.ccd
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected.cue
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected.dat
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected.img
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected.img_EdcEcc.txt
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected.scm
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected.sub
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected_disc.txt
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected_drive.txt
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected_img.cue
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected_mainError.txt
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected_mainInfo.txt
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected_sub.txt
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected_subError.txt
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected_subInfo.txt
ISO\CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]\Disc Not Detected_volDesc.txt
```

```
$  ls -1N "ISO/CodeWarrior - Academic Tools 96-97 [Plextor] [DIC]"
Disc Not Detected.bin
Disc Not Detected.c2
Disc Not Detected.ccd
Disc Not Detected.cue
Disc Not Detected.dat
Disc Not Detected.img
Disc Not Detected.img_EccEdc.txt
Disc Not Detected.scm
Disc Not Detected.sub
Disc Not Detected.toc
Disc Not Detected_20241001T225411.txt
Disc Not Detected_c2Error.txt
Disc Not Detected_disc.txt
Disc Not Detected_drive.txt
Disc Not Detected_img.cue
Disc Not Detected_mainError.txt
Disc Not Detected_mainInfo.txt
Disc Not Detected_subError.txt
Disc Not Detected_subInfo.txt
Disc Not Detected_subIntention.txt
Disc Not Detected_subReadable.txt
Disc Not Detected_suppl.dat
Disc Not Detected_volDesc.txt
```

</details>

**Additional context**
Redumper Log: [Disc Not Detected.log](https://github.com/user-attachments/files/17389701/Disc.Not.Detected.log)
DiscImageCreator text log copied from command prompt: [CodeWarrior - Academic Tools 96-97 [Plextor] [DIC].log](https://github.com/user-attachments/files/17389820/CodeWarrior.-.Academic.Tools.96-97.Plextor.DIC.log)

**Comment by Whovian9369** [comment]
Dump is unable to start now as trying to do so results in following error:

```
Scanning for drives..
Found 1 drives: D:\
Drive marked as empty, defaulting to CD-ROM.
Supported media speeds: 1, 2, 3, 4, 6, 8, 12, 16, 20, 24, 32, 40, 44, 48, 52, 56, 72
Setting drive speed to: 24
Local version: 3.2.2
Remote version: 3.2.2
You have the newest version!
Changed system to: Apple Macintosh
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Whovian\Downloads\Games\Tools\MPF.UI_net8.0-windows_win-x64_debug-2024_10_16\ISO\CodeWarrior\ -\ Academic\ Tools\ 96-97\ \[ASUS]\ \[Redumper]\Disc\ Not\ Detected_(\d{8})T\d{6}'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at MPF.Processors.RegexOutputFile.Exists() in /home/runner/work/MPF/MPF/MPF.Processors/RegexOutputFile.cs:line 54
   at MPF.Processors.BaseProcessor.CheckRequiredFiles(String basePath) in /home/runner/work/MPF/MPF/MPF.Processors/BaseProcessor.cs:line 352
   at MPF.Processors.BaseProcessor.FoundAllFiles(String outputDirectory, String outputFilename) in /home/runner/work/MPF/MPF/MPF.Processors/BaseProcessor.cs:line 187
   at MPF.Frontend.DumpEnvironment.CheckForMatchingProgram(String outputDirectory, String outputFilename) in /home/runner/work/MPF/MPF/MPF.Frontend/DumpEnvironment.cs:line 168
   at MPF.Frontend.ViewModels.MainViewModel.ValidateBeforeDumping() in /home/runner/work/MPF/MPF/MPF.Frontend/ViewModels/MainViewModel.cs:line 2222
   at MPF.Frontend.ViewModels.MainViewModel.StartDumping() in /home/runner/work/MPF/MPF/MPF.Frontend/ViewModels/MainViewModel.cs:line 2080
```
![image](https://github.com/user-attachments/assets/a6aacc5f-51dd-42d0-b3b7-da0d5adbd37f)
